################################################################################
# Base image
################################################################################

FROM nginx

################################################################################
# Build instructions
################################################################################

# Remove default nginx configs.
RUN rm -f /etc/nginx/conf.d/*

# Install packages
RUN apt-get update && apt-get install -my \
  supervisor \
  curl \
  wget \
  php5-curl \
  php5-fpm \
  php5-gd \
  php5-memcached \
  php5-mysql \
  php5-mcrypt \
  php5-sqlite \
  php5-xdebug \
  php-apc
  

# Ensure that PHP5 FPM is run as root.
RUN sed -i "s/user = www-data/user = root/" /etc/php5/fpm/pool.d/www.conf
RUN sed -i "s/group = www-data/group = root/" /etc/php5/fpm/pool.d/www.conf

# Pass all docker environment
RUN sed -i '/^;clear_env = no/s/^;//' /etc/php5/fpm/pool.d/www.conf

# Get access to FPM-ping page /ping
RUN sed -i '/^;ping\.path/s/^;//' /etc/php5/fpm/pool.d/www.conf
# Get access to FPM_Status page /status
RUN sed -i '/^;pm\.status_path/s/^;//' /etc/php5/fpm/pool.d/www.conf

# Prevent PHP Warning: 'xdebug' already loaded.
# XDebug loaded with the core
RUN sed -i '/.*xdebug.so$/s/^/;/' /etc/php5/mods-available/xdebug.ini

# Install HHVM
RUN apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0x5a16e7281be7a449
RUN echo deb http://dl.hhvm.com/debian jessie main | tee /etc/apt/sources.list.d/hhvm.list
RUN apt-get update && apt-get install -y hhvm

# Add configuration files
COPY php/config/nginx.conf /etc/nginx/
COPY php/config/default.vhost /etc/nginx/conf.d/
COPY php/config/supervisord.conf /etc/supervisor/conf.d/
COPY php/config/php.ini /etc/php5/fpm/conf.d/40-custom.ini

# install GIT
#RUN apt-get install -my git

# Install modman
#RUN curl -SL https://raw.githubusercontent.com/colinmollenhour/modman/master/modman -o modman \
#    && chmod +x ./modman \
#    && mv ./modman /usr/local/bin/

# Add modman wrapper
#COPY docker/development/frontend/files/modman-wrapper.sh /modman-wrapper.sh

#RUN chmod +x /modman-wrapper.sh

# install PHPUnit
#RUN apt-get install -my phpunit

# Resolve conflict users mysql
RUN sed -e 's/user.=.mysql/user=root/' -i /etc/mysql/my.cnf

################################################################################
# Application files
################################################################################
COPY www /var/www

################################################################################
# Ports
################################################################################

EXPOSE 80 443 9000

################################################################################
# Entrypoint
################################################################################

ENTRYPOINT ["/usr/bin/supervisord"]
