nginx:
  build: ./nginx/
  container_name: mage1_nginx
  ports:
    - 80:80
  links:
    - phpfpm
  volumes:
    - ./nginx/servers/:/etc/nginx/conf.d/
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./logs/nginx:/var/log/nginx
  volumes_from:
    - project

phpfpm:
  build: ./php/
  container_name: mage1_php
  ports:
    - 9000:9000
  links:
    - mysql
  volumes:
    - ./php/phpfpm.conf:/usr/local/etc/php-fpm.d/www.conf
    - ./logs/php:/var/log/php
  volumes_from:
    - project
  extra_hosts:
    - magento1.local:192.168.0.100

project:
  image: alpine:latest
  container_name: mage1_project
  volumes:
    - ~/Projects/magento-lab/1.9.4.2/clean/:/var/www/htdocs
  command: "true"

mysql:
  image: mysql:5.7
  container_name: mage1_mysql
  ports:
    - 3306:3306
  volumes:
    - ./data:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: secret_password
    MYSQL_DATABASE: magento1
    MYSQL_USER: magento1
    MYSQL_PASSWORD: a123456

phpmyadmin:
  image: phpmyadmin/phpmyadmin
  container_name: mage1_myadmin
  restart: always
  ports:
    - 8084:80
  links:
    - phpfpm
    - mysql
  environment:
    MYSQL_USERNAME: root
    MYSQL_ROOT_PASSWORD: secret_password
    PMA_HOST: mysql
    PMA_ARBITRARY: 1