version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: mage2_nginx
    ports:
      - "80:80"
    depends_on:
      - php
    volumes: &appvolumes
#     - {path_to_new_project:folder_into_container:delegated}
      - ~/Projects/magento-lab/2.3.2/clean:/magento2/:delegated
      - ~/Projects/magento-lab/2.3.2/sampledata:/magento_sampledata/:delegated
      - ./nginx/servers/:/etc/nginx/conf.d/
      - ./nginx/mage2.conf:/etc/nginx/mage2
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./dumps/install-magento-2.sh:/install-magento-2.sh
    networks:
      - network-back

  php:
    build: php
    container_name: mage2_php
    volumes: *appvolumes
    networks:
      - network-back

  db:
    image: mariadb
    container_name: mage2_mariadb
    volumes:
      - ./dumps/:/dumps/
      - ./mysql/data:/var/lib/mysql/
    ports:
      - "3306:3306"
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
    networks:
      - network-back

  app:
    # image: divante/vue-storefront-api:latest
    container_name: mage2_node
    build:
      context: .
      dockerfile: ./node/Dockerfile
    depends_on:
      - elastic
      - redis
    env_file: ./node/default.env
    environment:
      VS_ENV: dev
    volumes:
      - '~/Projects/pwa/storefront/api/config:/var/www/config'
      - '~/Projects/pwa/storefront/api/ecosystem.json:/var/www/ecosystem.json'
      - '~/Projects/pwa/storefront/api/migrations:/var/www/migrations'
      - '~/Projects/pwa/storefront/api/package.json:/var/www/package.json'
      - '~/Projects/pwa/storefront/api/babel.config.js:/var/www/babel.config.js'
      - '~/Projects/pwa/storefront/api/scripts:/var/www/scripts'
      - '~/Projects/pwa/storefront/api/src:/var/www/src'
      - '~/Projects/pwa/storefront/api/var:/var/www/var'
    tmpfs:
      - /var/www/dist
    links:
      - nginx:magento.sampledata.local
    ports:
      - '8080:8080'
    networks:
      - network-back

  elastic:
    build: elastic
    container_name: mage2_elastic
    volumes:
      - ./elastic/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elastic/data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"
    networks:
      - network-back

  kibana:
    build: kibana
    container_name: mage2_kibana
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - '5601:5601'
    networks:
      - network-back

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mage2_mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - network-back

  redis:
    image: 'redis:4-alpine'
    container_name: mage2_redis
    ports:
      - "6379:6379"
    networks:
      - network-back

networks:
  network-back:
    driver: bridge